name: Sync Tags
on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Tags from Upstream
        run: |
          git remote add upstream https://github.com/sub-store-org/Sub-Store-Front-End.git
          git fetch upstream --tags
          git push origin --tags
